vars:
    VERSION_NAME:
    VERSION_CODE:

platforms:
    ios:
        targets:
            App:
                version: '$VERSION_NAME'
                buildNumber: '$VERSION_CODE'
                bundleId: ev.ai.rnd.decisions
                displayName: AI Decisions
                # TODO: App -> Para ejecutarlo en livereload, cambiar para version en prod
                productName: App # productName: AI Decisions
                plist:
                    replace: true
                    entries:
                        - CFBundleURLTypes:
                              - CFBundleURLSchemes:
                                    - evaidec
                copy:
                    - src: ../../resources/ios/icon
                      dest: App/Assets.xcassets/AppIcon.appiconset
                    - src: ../../resources/ios/splash
                      dest: App/Assets.xcassets/Splash.imageset
    android:
        appName: AI Decisions
        versionName: "$VERSION_NAME"
        versionCode: "$VERSION_CODE"
        packageName: ev.ai.rnd.decisions
        gradle:
            - file: variables.gradle
              target:
                  ext:
              insertType: "variable"
              insert: |
                  minSdkVersion = 22
                  compileSdkVersion = 33
                  targetSdkVersion = 33
                  androidxAppCompatVersion =  '1.6.1'
                  androidxCoreVersion = '1.10.0'
                  androidxCoordinatorLayoutVersion = '1.2.0'
                  firebaseMessagingVersion = '23.0.5'
                  playServicesLocationVersion = '21.0.1'
                  junitVersion = '4.13.2'
                  androidxJunitVersion = '1.1.5'
                  androidxEspressoCoreVersion = '3.5.1'
                  cordovaAndroidVersion = '10.1.1'
                  coreSplashScreenVersion = '1.0.0'
        xml:
            - file: app/src/main/res/values/styles.xml
              target: resources/style[@name="AppTheme.NoActionBarLaunch"]
              inject: |
                  <item name="android:windowSplashScreenBackground">#141526</item>
        res:
            - path: drawable
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-land-hdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-land-mdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-land-xhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-land-xxhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-land-xxxhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-port-hdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-port-xhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-port-xxhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-port-xxxhdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: drawable-port-mdpi
              file: splash.png
              source: resources/android/splash/splash.png
            - path: mipmap-hdpi
              file: ic_launcher.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-hdpi
              file: ic_launcher_foreground.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-hdpi
              file: ic_launcher_round.png
              source: resources/android/icon/ic_launcher_round.png
            - path: mipmap-xxxhdpi
              file: ic_launcher.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xxxhdpi
              file: ic_launcher_foreground.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xxxhdpi
              file: ic_launcher_round.png
              source: resources/android/icon/ic_launcher_round.png
            - path: mipmap-xxhdpi
              file: ic_launcher.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xxhdpi
              file: ic_launcher_foreground.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xxhdpi
              file: ic_launcher_round.png
              source: resources/android/icon/ic_launcher_round.png
            - path: mipmap-xhdpi
              file: ic_launcher.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xhdpi
              file: ic_launcher_foreground.png
              source: resources/android/icon/ic_launcher.png
            - path: mipmap-xhdpi
              file: ic_launcher_round.png
              source: resources/android/icon/ic_launcher_round.png
