vars:
    VERSION_NAME:
    VERSION_CODE:

platforms:
    ios:
        targets:
            App:
                version: '$VERSION_NAME'
                buildNumber: '$VERSION_CODE'
                bundleId: ev.ai.rnd.decisions
                displayName: AI Decisions
                # TODO: App -> Para ejecutarlo en livereload, cambiar para version en prod
                productName: App # productName: AI Decisions
                plist:
                    replace: true
                    entries:
                        - CFBundleURLTypes:
                              - CFBundleURLSchemes:
                                    - evaidec
                copy:
                    - src: ../../resources/ios/icon
                      dest: App/Assets.xcassets/AppIcon.appiconset
                    - src: ../../resources/ios/splash
                      dest: App/Assets.xcassets/Splash.imageset